name: Deploy

on: 
  push:
      
jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI
    steps:
      - uses: actions/checkout@v2
      
      - name: Configure PHP 8.3
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.3
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml, zip, sqlite3
  
      # - name: Copy ENV file
      #   shell: bash
      #   env:
      #     ENV_FILE: ${{ secrets.LARAVEL_ENV }}
      #   run: 'echo "$ENV_FILE" > .env'

      - name: Copy testing ENV file
        shell: bash
        run: 'cp .env.example .env'
          
      - name: Install composer dependencies
        run: composer install
          
      - name: Install node dependencies
        run: npm ci
          
      - name: Build Frontend
        run: npm run build
      
      - name: Run tests
        run: php artisan key:generate
      
      - name: Run tests
        run: php artisan test --compact
        
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    name: CD
    steps:
      - uses: actions/checkout@v2

      # Initial setup
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      #Copy .env file
      - name: Copy ENV file
        shell: bash
        env:
          ENV_FILE: ${{ secrets.LARAVEL_ENV }}
        run: 'echo "$ENV_FILE" > .env'

      # Build docker image and push to Dockerhub
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/8.3/Dockerfile_build
          push: true
          tags: rogeriopereira/laravel_lambda:latest

      # Publish docker to ecr
      